#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Generated by scripts/205-install-xrt-ryzen-ai.sh
# Source before interactive NPU inference so VitisAI EP can load native libs.

if [[ -f /opt/xilinx/xrt/setup.sh ]]; then
  # shellcheck source=/dev/null
  source /opt/xilinx/xrt/setup.sh
fi
if [[ -d /opt/xilinx/xrt/bin ]]; then
  export PATH="/opt/xilinx/xrt/bin:${PATH}"
fi
if [[ -d "/home/gibboda/Documents/Projects/ai370-ubuntu-optimizer/.ai370-ai/ryzen-ai/venv" ]]; then
  export RYZEN_AI_INSTALLATION_PATH="/home/gibboda/Documents/Projects/ai370-ubuntu-optimizer/.ai370-ai/ryzen-ai/venv"
  # Same library layout AMD patches into the Ryzen AI venv activate script.
  _ai370_site="$(ls -d "${RYZEN_AI_INSTALLATION_PATH}"/lib/python*/site-packages 2>/dev/null | head -n1 || true)"
  if [[ -n "${_ai370_site}" ]]; then
    for _ai370_lib in \
      "${_ai370_site}/flexml/flexml_extras/lib" \
      "${_ai370_site}/onnxruntime/capi" \
      "${_ai370_site}/voe/lib"
    do
      if [[ -d "${_ai370_lib}" ]]; then
        case ":${LD_LIBRARY_PATH:-}:" in
          *":${_ai370_lib}:"*) ;;
          *) export LD_LIBRARY_PATH="${_ai370_lib}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" ;;
        esac
      fi
    done
  fi
  unset _ai370_site _ai370_lib
fi
