#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Generated by scripts/205-install-xrt-ryzen-ai.sh

if [[ -f /opt/xilinx/xrt/setup.sh ]]; then
  # shellcheck source=/dev/null
  source /opt/xilinx/xrt/setup.sh
fi
if [[ -d /opt/xilinx/xrt/bin ]]; then
  export PATH="/opt/xilinx/xrt/bin:${PATH}"
fi
if [[ -d "/home/gibboda/Documents/Projects/ai370-ubuntu-optimizer/.ai370-ai/ryzen-ai/venv" ]]; then
  export RYZEN_AI_INSTALLATION_PATH="/home/gibboda/Documents/Projects/ai370-ubuntu-optimizer/.ai370-ai/ryzen-ai/venv"
fi
